package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCSS_Declaration = createDescriptorForCSS_Declaration();
  /*package*/ final ConceptDescriptor myConceptCSS_Declaration_Block = createDescriptorForCSS_Declaration_Block();
  /*package*/ final ConceptDescriptor myConceptCSS_File = createDescriptorForCSS_File();
  /*package*/ final ConceptDescriptor myConceptCSS_Ruleset = createDescriptorForCSS_Ruleset();
  /*package*/ final ConceptDescriptor myConceptCSS_Selector = createDescriptorForCSS_Selector();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCSS_Declaration, myConceptCSS_Declaration_Block, myConceptCSS_File, myConceptCSS_Ruleset, myConceptCSS_Selector);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CSS_Declaration:
        return myConceptCSS_Declaration;
      case LanguageConceptSwitch.CSS_Declaration_Block:
        return myConceptCSS_Declaration_Block;
      case LanguageConceptSwitch.CSS_File:
        return myConceptCSS_File;
      case LanguageConceptSwitch.CSS_Ruleset:
        return myConceptCSS_Ruleset;
      case LanguageConceptSwitch.CSS_Selector:
        return myConceptCSS_Selector;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCSS_Declaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Declaration", 0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735aL);
    b.class_(false, false, false);
    b.origin("r:82f445e9-9333-4b8c-9edb-48b92a292d9a(CSS.structure)/1870710646446322522");
    b.version(2);
    b.property("property", 0x19f6196be6f9735fL).type(PrimitiveTypeId.STRING).origin("1870710646446322527").done();
    b.property("value", 0x19f6196be6f97361L).type(PrimitiveTypeId.STRING).origin("1870710646446322529").done();
    b.alias("declaration");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Declaration_Block() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Declaration_Block", 0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735bL);
    b.class_(false, false, false);
    b.origin("r:82f445e9-9333-4b8c-9edb-48b92a292d9a(CSS.structure)/1870710646446322523");
    b.version(2);
    b.aggregate("declarations", 0x19f6196be6f97364L).target(0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735aL).optional(true).ordered(true).multiple(true).origin("1870710646446322532").done();
    b.alias("declaration block");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_File() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_File", 0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735cL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:82f445e9-9333-4b8c-9edb-48b92a292d9a(CSS.structure)/1870710646446322524");
    b.version(2);
    b.aggregate("rulesets", 0x19f6196be6f97375L).target(0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735dL).optional(true).ordered(true).multiple(true).origin("1870710646446322549").done();
    b.alias("css file");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Ruleset() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Ruleset", 0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735dL);
    b.class_(false, false, false);
    b.origin("r:82f445e9-9333-4b8c-9edb-48b92a292d9a(CSS.structure)/1870710646446322525");
    b.version(2);
    b.aggregate("selectors", 0x19f6196be6f9736aL).target(0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735eL).optional(false).ordered(true).multiple(true).origin("1870710646446322538").done();
    b.aggregate("block", 0x19f6196be6f9736cL).target(0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735bL).optional(false).ordered(true).multiple(false).origin("1870710646446322540").done();
    b.alias("ruleset");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCSS_Selector() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CSS", "CSS_Selector", 0xb38e874f4c8f43a4L, 0x92d8990b98e3c7abL, 0x19f6196be6f9735eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:82f445e9-9333-4b8c-9edb-48b92a292d9a(CSS.structure)/1870710646446322526");
    b.version(2);
    b.alias("selector");
    return b.create();
  }
}
